version: '3'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  runevent:
    image: bot
    build:
      context: .
    depends_on:
      - db
    env_file:
      - .env
